#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

rob = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1B"
    "AACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5F"
    "VCB2My41LjEwMPRyoQAAA2lJREFUWEfNll1IU2EYx9cnBX0g3USXRhQI0UUUShdCQUHa1CQx"
    "QtB9yJbmB9Y2t7nZVmx2Y5hSNCOWtFAsMqEr6WJCMgfRZoxgaWCFiJaaw9zX0/+sTbZ1tp3j"
    "Ehr8EM953uf/O+/7ng+BYAN+RJQLCjiwaQPiBQIEdwMKBoOshEIh5jTz27omUFRNhaA+C87H"
    "mjECq6urNDAwwIrb7WYVmEM4ZUEQY3cwEjEBm81GbLhcLlaBpSzCY+I7/4lAqXiZJI12EjW8"
    "JaHoV8KslEvnSNb8mmqbRqhE7EuesTWBcDhMPp+PFb/fn3oGLtT4SaW5S3d1auptU1KLqhch"
    "4UiQULRCGu0d6tBp6YlWQYrWBykFmJChoSFWPB5PaoFK2WfS6/W0oKih8I0q6mlrpYuSH5Gg"
    "y3Jv5NwHlYwI555pr1OZeDFeImEG+vv7WfeAw+FILVAmWSCd7iaNt9bRtFJCt7W3iJkVRuDP"
    "OQMNalpoUlVLHRozFdeEUgo4nU5iwpKZmppKvwmr6lykVHeRQt0Tuer4zXlF/jGyLM1KK12q"
    "/ZZyCex2O42OjpLX6/2L2dnZjb0LAoFAt8FgIJPJxH8JsrwVI3uAETAajdTZ2UlxT73YVcf/"
    "TXgSvkH4zyyYwNgt0efAEbPZ/JzZsBaL5QvuhsG+vr5Fq9VKw8PDNhiciZL+XYAGUrAMfEnM"
    "4P896V4kOL8XvGIk1tC1M1K7OL+AUFwARliw4djmTI10Op0AdYcrhGO20yfnKT+PjmUak3Ae"
    "g6vAJAsTOLabazMEXwWMQAXXMZE6hFSCTywC7/hMJYIbowKVfAWYJXgP3Ekwy7KNazOEv4gK"
    "HEw5Bju4CHyNB0/A76XiJWKjuDo0k1R/lK05gk+BALCnFVaq7+WXiFfW9T2Ad0WoXm49i5A8"
    "cAKcA1LwCKxEOZ5WAFM6KGoYX5eApHGU5NKnzCZjw4PjhRmXCwL3FWrLugSUmh5quvZwDEEm"
    "oAEyIASH8vPC3D48IZCj17eb8QEyzedxjGWbxtgOsC/jVXIpQHgLHwHUarj05VyDhvuBn4dE"
    "LufmXAsR/pKjwDjXnrzqEF7OUaCJV2OuxQjfDuYzSASLq+kA15686xBuzCAwwrspnwEIzwWh"
    "NBJiPv141xq7SIDwx8DJggPHcng3/R8H/AY5mTgsGzqKMAAAAABJRU5ErkJggg==")
getrobData = rob.GetData
getrobImage = rob.GetImage
getrobBitmap = rob.GetBitmap
getrobIcon = rob.GetIcon

